---
title: "Journal (reproducible report)"
author: "Akshaya Katiganere Anandappa"
date: "2021-01-07"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

Last compiled: `r Sys.Date()`

# Intro to the tidyverse
## Challenge 1
```{r}

# 1.0 Load libraries ----
library(tidyverse)
library(readxl)

# 2.0 Importing Files ----
bikes_tbl      <- read_excel(path = "00_data/01_bike_sales/01_raw_data/bikes.xlsx")
orderlines_tbl <- read_excel("00_data/01_bike_sales/01_raw_data/orderlines.xlsx")
bikeshops_tbl  <- read_excel("00_data/01_bike_sales/01_raw_data/bikeshops.xlsx")

# 3.0 Examining Data ----
#orderlines_tbl
#glimpse(orderlines_tbl)

# 4.0 Joining Data ----
bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))


# 5.0 Wrangling Data ----
challenge_bike_orderlines_wrangled_tbl  <- bike_orderlines_joined_tbl %>%
  separate(col    = location,
           into   = c("city", "state"),
           sep    = ", ") %>%
  mutate(total.price = price * quantity) %>%
  
  select(-...1, -gender) %>%
  
  select(-ends_with(".id")) %>%
  
  bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>% 
  
  select(order.id, contains("order"), contains("model"), contains("category"),
         price, quantity, total.price,state,city,
         everything()) %>%
  
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))

# 6.0 Business Insights ----


# 6.1 Sales by state ----

# Step 1 - Manipulate
library(lubridate)
sales_by_state_tbl <- challenge_bike_orderlines_wrangled_tbl %>%
  select(state, total_price) %>%
  
  group_by(state) %>% 
  summarize(sales = sum(total_price))%>%
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

# Step 2 - Visualize
sales_by_state_tbl %>%
  ggplot(aes(x = state, y = sales)) +
  geom_col(fill = "#2DC6D6") + # Use geom_col for a bar plot
  geom_label(aes(label = sales_text)) + # Adding labels to the bars
  geom_smooth(method = "lm", se = FALSE) + # Adding a trendline
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title    = "Revenue by state",
    subtitle = "comparison",
    x = "", # Override defaults for x and y
    y = "Revenue"
  )

# 6.2 Sales by Year and state ----

# Step 1 - Manipulate
sales_by_year_state_tbl <- challenge_bike_orderlines_wrangled_tbl %>%
  
  select(order_date, total_price, state) %>%
  mutate(year = year(order_date)) %>%
  
  group_by(year, state) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))


# Step 2 - Visualize
sales_by_year_state_tbl %>%
  
  # Set up x, y, fill
  ggplot(aes(x = year, y = sales, fill = state)) +
  
  # Geometries
  geom_col() + # Run up to here to get a stacked bar plot
  
  # Facet
  facet_wrap(~ state) +
  
  # Formatting
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and state",
    subtitle = "A comparison",
    fill = "Main category" # Changes the legend name
  )    
  
```

# Data Acquisition

## Challenge 1 - to get data via api
```{r}
library(glue)
library(httr)
library(jsonlite)
resp <- GET("http://api.open-notify.org/iss-pass.json", query = list(lat =53.5511, lon = 9.9937))
resp
data = fromJSON(rawToChar(resp$content))
data
```

## Challenge 2 - competitor web scraping
```{r}
library(tidyverse) # Main Package - Loads dplyr, purrr, etc.
library(rvest)     # HTML Hacking & Web Scraping
library(xopen)     # Quickly opening URLs
library(jsonlite)  # converts JSON files to R objects
library(glue)      # concatenate strings
library(stringi)   # character string/text processing
library (dplyr)
url_home = "https://www.rosebikes.de/fahrräder/mtb"
html_home         <- read_html(url_home)
type_name <- html_home %>%
  html_nodes(css = ".catalog-category-bikes__title-text")%>%
  html_text()
               
type_price <-  html_home %>%
  html_nodes(css = ".catalog-category-bikes__price-title")%>%
  html_text()
name_list<-c()
price_list<-c()
#type_name_list= str_split(type_name," ")
for (i in type_name){
  
 elem<-str_extract(i,".+(?=\\n)")
 name_list<-c(name_list,elem)
}
for (i in type_price){
  
  elem<-str_extract(i,"(?<= ).+(?=\\S)")
  price_list<-c(price_list,elem)
  
}
#bike_table<- enframe(name =
#df <- ldply (price_list, data.frame)
bike_price_table<-data.frame(name_list,price_list)
bike_price_table
#a<-enframe(c(name=name_list,values=price_list))
```

# Data Visualization
## Challenge 1: Time course of the cumulative Covid-19 cases
```{r include=FALSE}
library(tidyverse)
library(vroom)
# Data Table
library(data.table)
# Counter
library(tictoc)
covid_data_tbl <- read_csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv")
#view(covid_data_tbl)
```

```{r include=FALSE}
covid_by_month_tbl <- covid_data_tbl %>%
  select(cases_weekly, countriesAndTerritories, dateRep) %>%
  filter(countriesAndTerritories %in% c("Germany","United_Kingdom","France","Spain","United_States_of_America")) %>%
  mutate(date       = lubridate::dmy(dateRep)) %>%
#mutate(date_floor  = floor_date(date, unit ="month")) %>%
#mutate(month = month(date)) %>%
group_by(countriesAndTerritories, date) %>%
    summarise(total_cases = cumsum(cases_weekly)) %>%
    ungroup() 
```

```{r plot5, fig.width=15, fig.height=7, echo=FALSE}
library(ggplot2)
library(scales)
covid_by_month_tbl%>%
ggplot(aes(x = date, y = total_cases, color = countriesAndTerritories)) +
  geom_line(size = 0.5) +
  expand_limits(y = 0) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  scale_y_continuous(labels = scales::dollar_format(scale = 1/1e6, 
                                                    prefix = "", 
                                                    suffix = " M")) +
  #scale_y_continuous(labels = scales::dollar_format(scale = 1e-6, 
   #                                                  prefix = "",
    #                                               suffix = "M "))
  
  labs(title = "Covid19 confirmed cases worldwide",
       x = "Year 2020",
       y = "Cumulitive cases")
```

## Challenge 2: Mortality Rate on world map
```{r include=FALSE}
  
  world <- map_data("world")
  covid_by_mortality_tbl <- covid_data_tbl %>%
  mutate(across(countriesAndTerritories, str_replace_all, "_", " ")) %>%
  mutate(countriesAndTerritories = case_when(
    countriesAndTerritories == "United Kingdom" ~ "UK",
    countriesAndTerritories == "United States of America" ~ "USA",
    countriesAndTerritories == "Czechia" ~ "Czech Republic",
    TRUE ~ countriesAndTerritories
  ))%>%
  group_by(countriesAndTerritories, popData2019, deaths_weekly) %>%
    summarise(total_pop = max(popData2019))%>%
    summarise(total_death = sum(deaths_weekly))%>%
  summarise(mortality =  (total_death)/(popData2019))
```

```{r include=FALSE}
class(covid_by_mortality_tbl)
setDT(covid_by_mortality_tbl)
class(covid_by_mortality_tbl)
covid_by_mortality_tbl %>% glimpse()
setDT(world)
world %>% glimpse()
```

```{r include=FALSE}
tic()
covid_by_map_tbl <- merge(x = world, y = covid_by_mortality_tbl, 
                      by.x = "region", by.y = "countriesAndTerritories",
                       all.x = TRUE, 
                       all.y = FALSE)
                      
    
toc()
covid_by_map_tbl%>% glimpse()
  
```

```{r include=FALSE}
setkey(covid_by_map_tbl, "region")
key(covid_by_map_tbl)
?setorder(region, -mortality, long, lat)
setorderv(covid_by_map_tbl, c("mortality", "region", "long", "lat"), order = -1)
```

```{r plot6, fig.width=15, fig.height=7, echo=FALSE}
library(ggplot2)
library(scales)
covid_by_map_tbl%>%
ggplot() +
  geom_map(aes(x = long, y = lat, map_id = region, fill = mortality),map = world) +
 scale_fill_continuous(labels = scales::percent)+
  labs(title = "Confirmed Covid19 deaths relative to size of the population ",
       subtitle = "More than 1.2 Million confirmed covid19 deaths worldwide") 
```


# Data Wrangling 

## Patent data
```{r include=FALSE}
# Tidyverse
library(tidyverse)
library(vroom)
# Data Table
library(data.table)
# Counter
library(tictoc)
```
```{r include=FALSE}
# 2.0 DATA IMPORT ----
library(vroom)
col_types_1 <- list(
  id = col_character(),
  date = col_date("%Y-%m-%d"),
  num_claims = col_double()
)
patent_tbl <- vroom(
            file       = "02_data_wrangling/patent.tsv", 
            delim      = "\t", 
            col_types  = col_types_1,
            na         = c("", "NA", "NULL")
        )
```

```{r include=FALSE}
# 2.0 DATA IMPORT ----
library(vroom)
col_types_2 <- list(
  patent_id = col_character(),
assignee_id = col_character()
)
patent_assignee_tbl <- vroom(
            file       = "02_data_wrangling/patent_assignee.tsv", 
            delim      = "\t", 
            col_types  = col_types_2,
            na         = c("", "NA", "NULL")
        )
```
```{r include=FALSE}
# 2.0 DATA IMPORT ----
library(vroom)
col_types_3 <- list(
  id = col_character(),
type = col_double(),
organization = col_character()
)
assignee_tbl <- vroom(
            file       = "02_data_wrangling/assignee.tsv", 
            delim      = "\t", 
            col_types  = col_types_3,
            na         = c("", "NA", "NULL")
        )
```
```{r include=FALSE}
# 2.0 DATA IMPORT ----
library(vroom)
col_types_4 <- list(
patent_id = col_character(),
mainclass_id = col_character(),
sequence = col_double()
)
uspc_tbl <- vroom(
            file       = "02_data_wrangling/uspc.tsv", 
            delim      = "\t", 
            col_types  = col_types_4,
            na         = c("", "NA", "NULL")
        )
```
```{r include=FALSE}
# 3.1 Patent Data ----
class(patent_tbl)
setDT(patent_tbl)
class(patent_tbl)
patent_tbl %>% glimpse()
setDT(patent_assignee_tbl)
patent_assignee_tbl %>% glimpse()
setDT(assignee_tbl)
assignee_tbl %>% glimpse()
setDT(uspc_tbl)
uspc_tbl %>% glimpse()
```
```{r include=FALSE}
# 4.0 DATA WRANGLING ----
# 4.1 Joining / Merging Data ----
tic()
patent_tbl_1 <- merge(x = patent_assignee_tbl, y = assignee_tbl, 
                      by.x = "assignee_id", by.y = "id",
                       all.x = TRUE, 
                       all.y = TRUE)
toc()
patent_tbl_1 %>% glimpse()
tic()
patent_tbl_2 <- merge(x = patent_tbl_1, y = patent_tbl,
                      by.x = "patent_id", by.y = "id",
                       all.x = TRUE,
                       all.y = TRUE)
toc()
patent_tbl_2 %>% glimpse()
tic()
patent_tbl_3 <- merge(x = patent_tbl_2, y = uspc_tbl,
                      by = "patent_id",
                       all.x = TRUE,  
                      all.y = TRUE)
toc()
patent_tbl_3 %>% glimpse()
```
```{r include=FALSE}
# Preparing the Data Table
setkey(patent_tbl_1, "type")
key(patent_tbl_1)
?setorder()
setorderv(patent_tbl_1, c("type", "organization"))
```
```{r include=FALSE}
# Preparing the Data Table
setkey(patent_tbl_2, "type")
key(patent_tbl_2)
?setorder()
setorderv(patent_tbl_2, c("type", "organization"))
```
```{r include=FALSE}
# Preparing the Data Table
setkey(patent_tbl_3, "type")
key(patent_tbl_3)
?setorder()
setorderv(patent_tbl_3, c("type", "organization"))
```
```{r include=FALSE}
# 5.1 Highest patents in US
patent_tbl_1_typ <- patent_tbl_1[ (type == '2'),] 
tic()
patent_US_Highest <- patent_tbl_1_typ[!is.na(organization), .N, by = organization]
toc()
setkey(patent_US_Highest, "organization")
key(patent_US_Highest)
?setorder(-N, organization)
setorderv(patent_US_Highest, c("N", "organization"), order = -1)
```
```{r echo=FALSE}
as_tibble(patent_US_Highest, .rows = 10)
```

```{r include=FALSE}
patent_tbl_2_typ <- patent_tbl_2[ !(type == 'na') & (type == '2') ]
patent_tbl_2_typ_month <- patent_tbl_2_typ %>%
select(organization, num_claims, date) %>%
  mutate(month = month(date))
patent_tbl_2_typ_January <- patent_tbl_2_typ_month[ (month == '1') ]
setkey(patent_tbl_2_typ_January, "organization")
key(patent_tbl_2_typ_January)
?setorder(-num_claims, organization)
setorderv(patent_tbl_2_typ_January, c("num_claims", "organization"), order = -1)
```

```{r echo=FALSE}
as_tibble(patent_tbl_2_typ_January, .rows = 10)
```

```{r include=FALSE}
patent_tbl_3_typ <- patent_tbl_3[!(type == 'na')]
patent_tbl_3_typ <- patent_tbl_3_typ[!(mainclass_id == 'na')]
setkey(patent_tbl_3_typ, "organization")
key(patent_tbl_3_typ)
?setorder(-num_claims, organization, -mainclass_id)
setorderv(patent_tbl_3_typ, c("num_claims", "organization", "mainclass_id"), order = -1)
```

```{r echo=FALSE}
as_tibble(patent_tbl_3_typ, .rows = 10)
```